---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      description: User id
      required: true
      schema:
        type: integer
    - name: post_id
      in: path
      description: Post id
      required: true
      schema:
        type: integer
    get:
      summary: list comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - comment
              - text
  "/api/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      description: User id
      required: true
      schema:
        type: string
    get:
      summary: list posts
      responses:
        '200':
          description: Returns all posts created by a given user.
          content:
            application/json:
              schema:
                type: array
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: string
                  comments_counter:
                    type: integer
                  likes_counter:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  author_id:
                    type: integer
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
